# Generated by Django 4.0.5 on 2022-06-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0003_alter_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
