# Generated by Django 4.0.5 on 2022-06-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0004_alter_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='fashion/'),
        ),
    ]
