# Generated by Django 4.0.5 on 2022-06-12 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_contact_form_single'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_form_single',
            name='post',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='travel.post'),
            preserve_default=False,
        ),
    ]
